Traceback (most recent call last):
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 782, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
    result = await obj
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/jupyter_client/channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 1005, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 806, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 856, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
list_of_nelts = np.array([20,50,200,500,2000,5000,20000,50000,200000]) # 
hmat_construct_time = list_of_nelts*0.
matvect_time = list_of_nelts*0.
h_compression = list_of_nelts*0.
i=0
for i in range(list_of_nelts.size):
    h,elasp = create_h_mat_2DS0(list_of_nelts[i],eta=3,max_leaf_size=64,eps_aca=1.e-4)
    matvect_time[i]= time_dot_product(h) 
    h_compression[i]=h.getCompression()
    hmat_construct_time[i]=elasp

-------------------

