Traceback (most recent call last):
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/bricelecampion/opt/anaconda3/envs/pyFracX-env/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#%% mesh a circle with gmsh with a refinement in the center.

center_res = 0.1
out_res = 0.02
Lx_ext = 1.

coor,conn=mesh_circle(Lx_ext,center_res,out_res )

## plotting the unstructured mesh
import matplotlib
triang=matplotlib.tri.Triangulation(coor[:,0], coor[:,1], triangles=conn, mask=None)
fig1, ax1 = plt.subplots()
ax1.set_aspect('equal')
ax1.triplot(triang, 'b-', lw=1)
ax1.plot(0.,0.,'ko')
plt.show()

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 7[0m
[1;32m      4[0m out_res [38;5;241m=[39m [38;5;241m0.02[39m
[1;32m      5[0m Lx_ext [38;5;241m=[39m [38;5;241m1.[39m
[0;32m----> 7[0m coor,conn[38;5;241m=[39m[43mmesh_circle[49m[43m([49m[43mLx_ext[49m[43m,[49m[43mcenter_res[49m[43m,[49m[43mout_res[49m[43m [49m[43m)[49m
[1;32m      9[0m [38;5;66;03m## plotting the unstructured mesh[39;00m
[1;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m

Cell [0;32mIn[2], line 48[0m, in [0;36mmesh_circle[0;34m(Lx_ext, center_res, out_res)[0m
[1;32m     46[0m swap_c[:,[38;5;241m0[39m][38;5;241m=[39mconn[:,[38;5;241m2[39m]
[1;32m     47[0m swap_c[:,[38;5;241m2[39m][38;5;241m=[39mconn[:,[38;5;241m0[39m]
[0;32m---> 48[0m conn[38;5;241m=[39m[43mswap_cs[49m
[1;32m     50[0m [38;5;28;01mreturn[39;00m coor,conn

[0;31mNameError[0m: name 'swap_cs' is not defined

